version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ooodmdk-app # менять имя ae взависимости от домена
    restart: unless-stopped
    ports:
      - "3016:4321" # не забыть переключать порты 3016 - 3023
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4321
      # Sanity переменные окружения
      - SANITY_PROJECT_ID=${SANITY_PROJECT_ID:-hngg8xd3}
      - SANITY_DATASET=${SANITY_DATASET:-production}
      - SANITY_API_VERSION=${SANITY_API_VERSION:-2023-05-03}
      - SANITY_TOKEN=${SANITY_TOKEN:-}
      # Дополнительные переменные
      - PUBLIC_SITE_URL=${PUBLIC_SITE_URL:-http://localhost:4321}
      # Postgres
      - POSTGRES_URL=${POSTGRES_URL}
      # Yandex Translate API
      - YANDEX_TRANSLATE_API_KEY=${YANDEX_TRANSLATE_API_KEY}
      - YANDEX_FOLDER_ID=${YANDEX_FOLDER_ID}
      - YANDEX_TRANSLATE_API_URL=${YANDEX_TRANSLATE_API_URL:-https://translate.api.cloud.yandex.net/translate/v2/translate}
    env_file:
      - stack.env
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:4321/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
    driver: local
